// Defines standardized feature tags for subscription packages.
// These tags are used to control access to various modules and functionalities.

// General Features
const String FT_CAN_MANAGE_USERS = 'CAN_MANAGE_USERS';
const String FT_CAN_SEND_ANNOUNCEMENTS = 'CAN_SEND_ANNOUNCEMENTS';
const String FT_HAS_BASIC_REPORTS = 'HAS_BASIC_REPORTS';
const String FT_HAS_ADVANCED_REPORTS = 'HAS_ADVANCED_REPORTS';
const String FT_CAN_CUSTOMIZE_BRANDING = 'CAN_CUSTOMIZE_BRANDING'; // e.g., logo, colors

// Academic Features
const String FT_CAN_MANAGE_ACADEMIC_YEARS = 'CAN_MANAGE_ACADEMIC_YEARS';
const String FT_CAN_MANAGE_DEPARTMENTS = 'CAN_MANAGE_DEPARTMENTS';
const String FT_CAN_MANAGE_CLASSES = 'CAN_MANAGE_CLASSES';
const String FT_CAN_MANAGE_SUBJECTS = 'CAN_MANAGE_SUBJECTS';
const String FT_CAN_MANAGE_TIMETABLES = 'CAN_MANAGE_TIMETABLES';
const String FT_CAN_MANAGE_ATTENDANCE = 'CAN_MANAGE_ATTENDANCE';
const String FT_CAN_MANAGE_GRADING = 'CAN_MANAGE_GRADING';
const String FT_CAN_GENERATE_REPORT_CARDS = 'CAN_GENERATE_REPORT_CARDS';
const String FT_HAS_ONLINE_LEARNING_MODULE = 'HAS_ONLINE_LEARNING_MODULE';
const String FT_HAS_ONLINE_EXAMS_MODULE = 'HAS_ONLINE_EXAMS_MODULE';

// Financial Features
const String FT_CAN_MANAGE_FEE_STRUCTURES = 'CAN_MANAGE_FEE_STRUCTURES';
const String FT_CAN_PROCESS_ONLINE_PAYMENTS = 'CAN_PROCESS_ONLINE_PAYMENTS'; // e.g. Mpesa
const String FT_CAN_GENERATE_FINANCIAL_REPORTS = 'CAN_GENERATE_FINANCIAL_REPORTS';
const String FT_CAN_MANAGE_PAYROLL = 'CAN_MANAGE_PAYROLL'; // For staff

// Communication Features
const String FT_HAS_PARENT_PORTAL = 'HAS_PARENT_PORTAL';
const String FT_HAS_INTERNAL_MESSAGING = 'HAS_INTERNAL_MESSAGING';
const String FT_CAN_SEND_SMS_NOTIFICATIONS = 'CAN_SEND_SMS_NOTIFICATIONS';
const String FT_CAN_SEND_EMAIL_NOTIFICATIONS = 'CAN_SEND_EMAIL_NOTIFICATIONS';

// Limits (can be paired with numerical values in the package model)
// The presence of the tag means the limit type is active for the package.
// The actual numerical limit (e.g., 500) is stored in maxStudents, maxStaff.
const String FT_LIMIT_STUDENTS = 'LIMIT_STUDENTS';
const String FT_LIMIT_STAFF = 'LIMIT_STAFF';
const String FT_LIMIT_STORAGE_MB = 'LIMIT_STORAGE_MB';

// Add more feature tags as the system grows.
// Example:
// const String FT_CAN_VIEW_SYSTEM_LOGS = 'CAN_VIEW_SYSTEM_LOGS';

// It's useful to have a list of all defined tags for UI generation (e.g. in forms)
const List<String> allFeatureTags = [
  FT_CAN_MANAGE_USERS,
  FT_CAN_SEND_ANNOUNCEMENTS,
  FT_HAS_BASIC_REPORTS,
  FT_HAS_ADVANCED_REPORTS,
  FT_CAN_CUSTOMIZE_BRANDING,
  FT_CAN_MANAGE_ACADEMIC_YEARS,
  FT_CAN_MANAGE_DEPARTMENTS,
  FT_CAN_MANAGE_CLASSES,
  FT_CAN_MANAGE_SUBJECTS,
  FT_CAN_MANAGE_TIMETABLES,
  FT_CAN_MANAGE_ATTENDANCE,
  FT_CAN_MANAGE_GRADING,
  FT_CAN_GENERATE_REPORT_CARDS,
  FT_HAS_ONLINE_LEARNING_MODULE,
  FT_HAS_ONLINE_EXAMS_MODULE,
  FT_CAN_MANAGE_FEE_STRUCTURES,
  FT_CAN_PROCESS_ONLINE_PAYMENTS,
  FT_CAN_GENERATE_FINANCIAL_REPORTS,
  FT_CAN_MANAGE_PAYROLL,
  FT_HAS_PARENT_PORTAL,
  FT_HAS_INTERNAL_MESSAGING,
  FT_CAN_SEND_SMS_NOTIFICATIONS,
  FT_CAN_SEND_EMAIL_NOTIFICATIONS,
  FT_LIMIT_STUDENTS,
  FT_LIMIT_STAFF,
  FT_LIMIT_STORAGE_MB,
];
